# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ELFIN_Proto.ui'
#
# Created: Sun Jan 17 20:04:42 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(824, 690)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabControl = QtGui.QTabWidget(self.centralwidget)
        self.tabControl.setGeometry(QtCore.QRect(10, 30, 791, 391))
        self.tabControl.setObjectName(_fromUtf8("tabControl"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.schedule_viewer_group_box = QtGui.QGroupBox(self.tab)
        self.schedule_viewer_group_box.setGeometry(QtCore.QRect(0, 0, 781, 341))
        self.schedule_viewer_group_box.setTitle(_fromUtf8(""))
        self.schedule_viewer_group_box.setObjectName(_fromUtf8("schedule_viewer_group_box"))
        self.label = QtGui.QLabel(self.schedule_viewer_group_box)
        self.label.setGeometry(QtCore.QRect(10, 80, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.label_4.setGeometry(QtCore.QRect(10, 230, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.label_5.setGeometry(QtCore.QRect(10, 280, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.schedule_viewer_label = QtGui.QLabel(self.schedule_viewer_group_box)
        self.schedule_viewer_label.setGeometry(QtCore.QRect(70, 20, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.schedule_viewer_label.setFont(font)
        self.schedule_viewer_label.setObjectName(_fromUtf8("schedule_viewer_label"))
        self.example_zone_2 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_zone_2.setGeometry(QtCore.QRect(330, 50, 441, 261))
        self.example_zone_2.setStyleSheet(_fromUtf8("QLabel { background-color : rgb(225, 249, 255); color : black; }"))
        self.example_zone_2.setText(_fromUtf8(""))
        self.example_zone_2.setObjectName(_fromUtf8("example_zone_2"))
        self.example_event_1 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_event_1.setGeometry(QtCore.QRect(316, 50, 20, 261))
        self.example_event_1.setStyleSheet(_fromUtf8("QLabel { background-color : rgb(255, 160, 160); color : black; }"))
        self.example_event_1.setText(_fromUtf8(""))
        self.example_event_1.setObjectName(_fromUtf8("example_event_1"))
        self.example_zone_1 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_zone_1.setGeometry(QtCore.QRect(70, 50, 251, 261))
        self.example_zone_1.setStyleSheet(_fromUtf8("QLabel { background-color :rgb(250, 255, 198); color : black; }"))
        self.example_zone_1.setText(_fromUtf8(""))
        self.example_zone_1.setObjectName(_fromUtf8("example_zone_1"))
        self.horizontal_line_4 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.horizontal_line_4.setGeometry(QtCore.QRect(70, 230, 701, 16))
        self.horizontal_line_4.setFrameShape(QtGui.QFrame.HLine)
        self.horizontal_line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.horizontal_line_4.setObjectName(_fromUtf8("horizontal_line_4"))
        self.horizontal_line_1 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.horizontal_line_1.setGeometry(QtCore.QRect(70, 80, 701, 16))
        self.horizontal_line_1.setFrameShape(QtGui.QFrame.HLine)
        self.horizontal_line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.horizontal_line_1.setObjectName(_fromUtf8("horizontal_line_1"))
        self.horizontal_line_5 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.horizontal_line_5.setGeometry(QtCore.QRect(70, 280, 701, 16))
        self.horizontal_line_5.setFrameShape(QtGui.QFrame.HLine)
        self.horizontal_line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.horizontal_line_5.setObjectName(_fromUtf8("horizontal_line_5"))
        self.horizontal_line_3 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.horizontal_line_3.setGeometry(QtCore.QRect(70, 180, 701, 16))
        self.horizontal_line_3.setFrameShape(QtGui.QFrame.HLine)
        self.horizontal_line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.horizontal_line_3.setObjectName(_fromUtf8("horizontal_line_3"))
        self.horizontal_line_2 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.horizontal_line_2.setGeometry(QtCore.QRect(70, 130, 701, 16))
        self.horizontal_line_2.setFrameShape(QtGui.QFrame.HLine)
        self.horizontal_line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.horizontal_line_2.setObjectName(_fromUtf8("horizontal_line_2"))
        self.example_time_label_1 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_time_label_1.setGeometry(QtCore.QRect(70, 320, 52, 15))
        self.example_time_label_1.setObjectName(_fromUtf8("example_time_label_1"))
        self.example_time_label_2 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_time_label_2.setGeometry(QtCore.QRect(140, 320, 52, 15))
        self.example_time_label_2.setObjectName(_fromUtf8("example_time_label_2"))
        self.example_time_label_3 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_time_label_3.setGeometry(QtCore.QRect(210, 320, 52, 15))
        self.example_time_label_3.setObjectName(_fromUtf8("example_time_label_3"))
        self.example_time_label_4 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_time_label_4.setGeometry(QtCore.QRect(280, 320, 52, 15))
        self.example_time_label_4.setObjectName(_fromUtf8("example_time_label_4"))
        self.example_time_label_5 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_time_label_5.setGeometry(QtCore.QRect(350, 320, 52, 15))
        self.example_time_label_5.setObjectName(_fromUtf8("example_time_label_5"))
        self.example_time_label_6 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_time_label_6.setGeometry(QtCore.QRect(420, 320, 52, 15))
        self.example_time_label_6.setObjectName(_fromUtf8("example_time_label_6"))
        self.example_time_label_7 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_time_label_7.setGeometry(QtCore.QRect(490, 320, 52, 15))
        self.example_time_label_7.setObjectName(_fromUtf8("example_time_label_7"))
        self.example_time_label_8 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_time_label_8.setGeometry(QtCore.QRect(560, 320, 52, 15))
        self.example_time_label_8.setObjectName(_fromUtf8("example_time_label_8"))
        self.example_time_label_9 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_time_label_9.setGeometry(QtCore.QRect(630, 320, 52, 15))
        self.example_time_label_9.setObjectName(_fromUtf8("example_time_label_9"))
        self.example_time_label_10 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_time_label_10.setGeometry(QtCore.QRect(700, 320, 52, 15))
        self.example_time_label_10.setObjectName(_fromUtf8("example_time_label_10"))
        self.vertical_line_1 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.vertical_line_1.setGeometry(QtCore.QRect(80, 50, 20, 261))
        self.vertical_line_1.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_1.setObjectName(_fromUtf8("vertical_line_1"))
        self.vertical_line_2 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.vertical_line_2.setGeometry(QtCore.QRect(150, 50, 20, 261))
        self.vertical_line_2.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_2.setObjectName(_fromUtf8("vertical_line_2"))
        self.vertical_line_3 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.vertical_line_3.setGeometry(QtCore.QRect(220, 50, 20, 261))
        self.vertical_line_3.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_3.setObjectName(_fromUtf8("vertical_line_3"))
        self.vertical_line_4 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.vertical_line_4.setGeometry(QtCore.QRect(290, 50, 20, 261))
        self.vertical_line_4.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_4.setObjectName(_fromUtf8("vertical_line_4"))
        self.vertical_line_5 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.vertical_line_5.setGeometry(QtCore.QRect(360, 50, 20, 261))
        self.vertical_line_5.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_5.setObjectName(_fromUtf8("vertical_line_5"))
        self.vertical_line_6 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.vertical_line_6.setGeometry(QtCore.QRect(430, 50, 20, 261))
        self.vertical_line_6.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_6.setObjectName(_fromUtf8("vertical_line_6"))
        self.vertical_line_7 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.vertical_line_7.setGeometry(QtCore.QRect(500, 50, 20, 261))
        self.vertical_line_7.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_7.setObjectName(_fromUtf8("vertical_line_7"))
        self.vertical_line_8 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.vertical_line_8.setGeometry(QtCore.QRect(570, 50, 20, 261))
        self.vertical_line_8.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_8.setObjectName(_fromUtf8("vertical_line_8"))
        self.vertical_line_9 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.vertical_line_9.setGeometry(QtCore.QRect(640, 50, 20, 261))
        self.vertical_line_9.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_9.setObjectName(_fromUtf8("vertical_line_9"))
        self.vertical_line_10 = QtGui.QFrame(self.schedule_viewer_group_box)
        self.vertical_line_10.setGeometry(QtCore.QRect(710, 50, 20, 261))
        self.vertical_line_10.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_10.setObjectName(_fromUtf8("vertical_line_10"))
        self.example_activity_label_1 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_activity_label_1.setGeometry(QtCore.QRect(90, 80, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.example_activity_label_1.setFont(font)
        self.example_activity_label_1.setStyleSheet(_fromUtf8("QLabel { background-color : rgb(169, 253, 248); color : black; }"))
        self.example_activity_label_1.setObjectName(_fromUtf8("example_activity_label_1"))
        self.example_activity_label_2 = QtGui.QLabel(self.schedule_viewer_group_box)
        self.example_activity_label_2.setGeometry(QtCore.QRect(250, 130, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.example_activity_label_2.setFont(font)
        self.example_activity_label_2.setStyleSheet(_fromUtf8("QLabel { background-color : rgb(255, 255, 0); color : black; }"))
        self.example_activity_label_2.setObjectName(_fromUtf8("example_activity_label_2"))
        self.schedule_viewer_scroll_bar = QtGui.QScrollBar(self.tab)
        self.schedule_viewer_scroll_bar.setGeometry(QtCore.QRect(70, 340, 701, 20))
        self.schedule_viewer_scroll_bar.setMaximum(50)
        self.schedule_viewer_scroll_bar.setOrientation(QtCore.Qt.Horizontal)
        self.schedule_viewer_scroll_bar.setObjectName(_fromUtf8("schedule_viewer_scroll_bar"))
        self.tabControl.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.schedule_creator_group_box = QtGui.QGroupBox(self.tab_2)
        self.schedule_creator_group_box.setGeometry(QtCore.QRect(0, 0, 781, 341))
        self.schedule_creator_group_box.setTitle(_fromUtf8(""))
        self.schedule_creator_group_box.setObjectName(_fromUtf8("schedule_creator_group_box"))
        self.label_6 = QtGui.QLabel(self.schedule_creator_group_box)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.schedule_creator_group_box)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.schedule_creator_group_box)
        self.label_8.setGeometry(QtCore.QRect(10, 180, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.schedule_creator_group_box)
        self.label_9.setGeometry(QtCore.QRect(10, 230, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.schedule_creator_group_box)
        self.label_10.setGeometry(QtCore.QRect(10, 280, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.schedule_viewer_label_2 = QtGui.QLabel(self.schedule_creator_group_box)
        self.schedule_viewer_label_2.setGeometry(QtCore.QRect(70, 20, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.schedule_viewer_label_2.setFont(font)
        self.schedule_viewer_label_2.setObjectName(_fromUtf8("schedule_viewer_label_2"))
        self.example_zone_3 = QtGui.QLabel(self.schedule_creator_group_box)
        self.example_zone_3.setGeometry(QtCore.QRect(330, 50, 441, 261))
        self.example_zone_3.setStyleSheet(_fromUtf8("QLabel { background-color : rgb(225, 249, 255); color : black; }"))
        self.example_zone_3.setText(_fromUtf8(""))
        self.example_zone_3.setObjectName(_fromUtf8("example_zone_3"))
        self.example_event_2 = QtGui.QLabel(self.schedule_creator_group_box)
        self.example_event_2.setGeometry(QtCore.QRect(315, 50, 21, 261))
        self.example_event_2.setStyleSheet(_fromUtf8("QLabel { background-color : rgb(255, 160, 160); color : black; }"))
        self.example_event_2.setText(_fromUtf8(""))
        self.example_event_2.setObjectName(_fromUtf8("example_event_2"))
        self.example_zone_4 = QtGui.QLabel(self.schedule_creator_group_box)
        self.example_zone_4.setGeometry(QtCore.QRect(70, 50, 251, 261))
        self.example_zone_4.setStyleSheet(_fromUtf8("QLabel { background-color :rgb(250, 255, 198); color : black; }"))
        self.example_zone_4.setText(_fromUtf8(""))
        self.example_zone_4.setObjectName(_fromUtf8("example_zone_4"))
        self.horizontal_line_6 = QtGui.QFrame(self.schedule_creator_group_box)
        self.horizontal_line_6.setGeometry(QtCore.QRect(70, 230, 701, 16))
        self.horizontal_line_6.setFrameShape(QtGui.QFrame.HLine)
        self.horizontal_line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.horizontal_line_6.setObjectName(_fromUtf8("horizontal_line_6"))
        self.horizontal_line_7 = QtGui.QFrame(self.schedule_creator_group_box)
        self.horizontal_line_7.setGeometry(QtCore.QRect(70, 80, 701, 16))
        self.horizontal_line_7.setFrameShape(QtGui.QFrame.HLine)
        self.horizontal_line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.horizontal_line_7.setObjectName(_fromUtf8("horizontal_line_7"))
        self.horizontal_line_8 = QtGui.QFrame(self.schedule_creator_group_box)
        self.horizontal_line_8.setGeometry(QtCore.QRect(70, 280, 701, 16))
        self.horizontal_line_8.setFrameShape(QtGui.QFrame.HLine)
        self.horizontal_line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.horizontal_line_8.setObjectName(_fromUtf8("horizontal_line_8"))
        self.horizontal_line_9 = QtGui.QFrame(self.schedule_creator_group_box)
        self.horizontal_line_9.setGeometry(QtCore.QRect(70, 180, 701, 16))
        self.horizontal_line_9.setFrameShape(QtGui.QFrame.HLine)
        self.horizontal_line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.horizontal_line_9.setObjectName(_fromUtf8("horizontal_line_9"))
        self.horizontal_line_10 = QtGui.QFrame(self.schedule_creator_group_box)
        self.horizontal_line_10.setGeometry(QtCore.QRect(70, 130, 701, 16))
        self.horizontal_line_10.setFrameShape(QtGui.QFrame.HLine)
        self.horizontal_line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.horizontal_line_10.setObjectName(_fromUtf8("horizontal_line_10"))
        self.example_time_label_11 = QtGui.QLabel(self.schedule_creator_group_box)
        self.example_time_label_11.setGeometry(QtCore.QRect(70, 320, 52, 15))
        self.example_time_label_11.setObjectName(_fromUtf8("example_time_label_11"))
        self.example_time_label_12 = QtGui.QLabel(self.schedule_creator_group_box)
        self.example_time_label_12.setGeometry(QtCore.QRect(140, 320, 52, 15))
        self.example_time_label_12.setObjectName(_fromUtf8("example_time_label_12"))
        self.example_time_label_13 = QtGui.QLabel(self.schedule_creator_group_box)
        self.example_time_label_13.setGeometry(QtCore.QRect(210, 320, 52, 15))
        self.example_time_label_13.setObjectName(_fromUtf8("example_time_label_13"))
        self.example_time_label_14 = QtGui.QLabel(self.schedule_creator_group_box)
        self.example_time_label_14.setGeometry(QtCore.QRect(280, 320, 52, 15))
        self.example_time_label_14.setObjectName(_fromUtf8("example_time_label_14"))
        self.example_time_label_15 = QtGui.QLabel(self.schedule_creator_group_box)
        self.example_time_label_15.setGeometry(QtCore.QRect(350, 320, 52, 15))
        self.example_time_label_15.setObjectName(_fromUtf8("example_time_label_15"))
        self.example_time_label_16 = QtGui.QLabel(self.schedule_creator_group_box)
        self.example_time_label_16.setGeometry(QtCore.QRect(420, 320, 52, 15))
        self.example_time_label_16.setObjectName(_fromUtf8("example_time_label_16"))
        self.example_time_label_17 = QtGui.QLabel(self.schedule_creator_group_box)
        self.example_time_label_17.setGeometry(QtCore.QRect(490, 320, 52, 15))
        self.example_time_label_17.setObjectName(_fromUtf8("example_time_label_17"))
        self.example_time_label_18 = QtGui.QLabel(self.schedule_creator_group_box)
        self.example_time_label_18.setGeometry(QtCore.QRect(560, 320, 52, 15))
        self.example_time_label_18.setObjectName(_fromUtf8("example_time_label_18"))
        self.example_time_label_19 = QtGui.QLabel(self.schedule_creator_group_box)
        self.example_time_label_19.setGeometry(QtCore.QRect(630, 320, 52, 15))
        self.example_time_label_19.setObjectName(_fromUtf8("example_time_label_19"))
        self.example_time_label_20 = QtGui.QLabel(self.schedule_creator_group_box)
        self.example_time_label_20.setGeometry(QtCore.QRect(700, 320, 52, 15))
        self.example_time_label_20.setObjectName(_fromUtf8("example_time_label_20"))
        self.vertical_line_11 = QtGui.QFrame(self.schedule_creator_group_box)
        self.vertical_line_11.setGeometry(QtCore.QRect(80, 50, 20, 261))
        self.vertical_line_11.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_11.setObjectName(_fromUtf8("vertical_line_11"))
        self.vertical_line_12 = QtGui.QFrame(self.schedule_creator_group_box)
        self.vertical_line_12.setGeometry(QtCore.QRect(150, 50, 20, 261))
        self.vertical_line_12.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_12.setObjectName(_fromUtf8("vertical_line_12"))
        self.vertical_line_13 = QtGui.QFrame(self.schedule_creator_group_box)
        self.vertical_line_13.setGeometry(QtCore.QRect(220, 50, 20, 261))
        self.vertical_line_13.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_13.setObjectName(_fromUtf8("vertical_line_13"))
        self.vertical_line_14 = QtGui.QFrame(self.schedule_creator_group_box)
        self.vertical_line_14.setGeometry(QtCore.QRect(290, 50, 20, 261))
        self.vertical_line_14.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_14.setObjectName(_fromUtf8("vertical_line_14"))
        self.vertical_line_15 = QtGui.QFrame(self.schedule_creator_group_box)
        self.vertical_line_15.setGeometry(QtCore.QRect(360, 50, 20, 261))
        self.vertical_line_15.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_15.setObjectName(_fromUtf8("vertical_line_15"))
        self.vertical_line_16 = QtGui.QFrame(self.schedule_creator_group_box)
        self.vertical_line_16.setGeometry(QtCore.QRect(430, 50, 20, 261))
        self.vertical_line_16.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_16.setObjectName(_fromUtf8("vertical_line_16"))
        self.vertical_line_17 = QtGui.QFrame(self.schedule_creator_group_box)
        self.vertical_line_17.setGeometry(QtCore.QRect(500, 50, 20, 261))
        self.vertical_line_17.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_17.setObjectName(_fromUtf8("vertical_line_17"))
        self.vertical_line_18 = QtGui.QFrame(self.schedule_creator_group_box)
        self.vertical_line_18.setGeometry(QtCore.QRect(570, 50, 20, 261))
        self.vertical_line_18.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_18.setObjectName(_fromUtf8("vertical_line_18"))
        self.vertical_line_19 = QtGui.QFrame(self.schedule_creator_group_box)
        self.vertical_line_19.setGeometry(QtCore.QRect(640, 50, 20, 261))
        self.vertical_line_19.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_19.setObjectName(_fromUtf8("vertical_line_19"))
        self.vertical_line_20 = QtGui.QFrame(self.schedule_creator_group_box)
        self.vertical_line_20.setGeometry(QtCore.QRect(710, 50, 20, 261))
        self.vertical_line_20.setFrameShape(QtGui.QFrame.VLine)
        self.vertical_line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.vertical_line_20.setObjectName(_fromUtf8("vertical_line_20"))
        self.add_activity_button = QtGui.QPushButton(self.schedule_creator_group_box)
        self.add_activity_button.setGeometry(QtCore.QRect(644, 20, 131, 27))
        self.add_activity_button.setFlat(False)
        self.add_activity_button.setObjectName(_fromUtf8("add_activity_button"))
        self.example_activity_button_1 = QtGui.QPushButton(self.schedule_creator_group_box)
        self.example_activity_button_1.setGeometry(QtCore.QRect(90, 80, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.example_activity_button_1.setFont(font)
        self.example_activity_button_1.setStyleSheet(_fromUtf8("QPushButton { background-color : rgb(169, 253, 248);  color: black; border: 2px;}"))
        self.example_activity_button_1.setFlat(False)
        self.example_activity_button_1.setObjectName(_fromUtf8("example_activity_button_1"))
        self.example_activity_button_2 = QtGui.QPushButton(self.schedule_creator_group_box)
        self.example_activity_button_2.setGeometry(QtCore.QRect(270, 130, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.example_activity_button_2.setFont(font)
        self.example_activity_button_2.setStyleSheet(_fromUtf8("QPushButton { background-color : rgb(255, 255, 0);  color: black; border: 2px;}"))
        self.example_activity_button_2.setFlat(False)
        self.example_activity_button_2.setObjectName(_fromUtf8("example_activity_button_2"))
        self.schedule_viewer_scroll_bar_2 = QtGui.QScrollBar(self.tab_2)
        self.schedule_viewer_scroll_bar_2.setGeometry(QtCore.QRect(70, 340, 701, 20))
        self.schedule_viewer_scroll_bar_2.setMaximum(50)
        self.schedule_viewer_scroll_bar_2.setOrientation(QtCore.Qt.Horizontal)
        self.schedule_viewer_scroll_bar_2.setObjectName(_fromUtf8("schedule_viewer_scroll_bar_2"))
        self.tabControl.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.graphics_scene_test_view = QtGui.QGraphicsView(self.tab_5)
        self.graphics_scene_test_view.setGeometry(QtCore.QRect(50, 30, 681, 301))
        self.graphics_scene_test_view.setDragMode(QtGui.QGraphicsView.NoDrag)
        self.graphics_scene_test_view.setObjectName(_fromUtf8("graphics_scene_test_view"))
        self.tabControl.addTab(self.tab_5, _fromUtf8(""))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 430, 791, 211))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.console_text_edit = QtGui.QTextEdit(self.tab_3)
        self.console_text_edit.setGeometry(QtCore.QRect(0, 0, 791, 181))
        self.console_text_edit.setReadOnly(True)
        self.console_text_edit.setObjectName(_fromUtf8("console_text_edit"))
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.console_line_edit = QtGui.QLineEdit(self.tab_4)
        self.console_line_edit.setEnabled(True)
        self.console_line_edit.setGeometry(QtCore.QRect(0, 150, 791, 27))
        self.console_line_edit.setObjectName(_fromUtf8("console_line_edit"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.help_button = QtGui.QPushButton(self.centralwidget)
        self.help_button.setGeometry(QtCore.QRect(720, 0, 85, 27))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabControl.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ELFIN Proto GUI", None))
        self.label.setText(_translate("MainWindow", "Thing", None))
        self.label_2.setText(_translate("MainWindow", "Thing 2", None))
        self.label_3.setText(_translate("MainWindow", "Thing 3", None))
        self.label_4.setText(_translate("MainWindow", "Thing 4", None))
        self.label_5.setText(_translate("MainWindow", "Thing 5", None))
        self.schedule_viewer_label.setText(_translate("MainWindow", "Schedule Viewer", None))
        self.example_zone_2.setToolTip(_translate("MainWindow", "some other zone", None))
        self.example_event_1.setToolTip(_translate("MainWindow", "some event", None))
        self.example_zone_1.setToolTip(_translate("MainWindow", "some zone", None))
        self.example_time_label_1.setText(_translate("MainWindow", "12:00 AM", None))
        self.example_time_label_2.setText(_translate("MainWindow", "12:15 AM", None))
        self.example_time_label_3.setText(_translate("MainWindow", "12:30 AM", None))
        self.example_time_label_4.setText(_translate("MainWindow", "12:45 AM", None))
        self.example_time_label_5.setText(_translate("MainWindow", "1:00 AM", None))
        self.example_time_label_6.setText(_translate("MainWindow", "1:15 AM", None))
        self.example_time_label_7.setText(_translate("MainWindow", "1:30 AM", None))
        self.example_time_label_8.setText(_translate("MainWindow", "1:45 AM", None))
        self.example_time_label_9.setText(_translate("MainWindow", "2:00 AM", None))
        self.example_time_label_10.setText(_translate("MainWindow", "2:15 AM", None))
        self.example_activity_label_1.setToolTip(_translate("MainWindow", "This  is an example status for an activity", None))
        self.example_activity_label_1.setText(_translate("MainWindow", "example_activity", None))
        self.example_activity_label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>LENGTH: 15 </p><p>START TIME: 10:22 </p><p>END TIME: 10:37</p><p><br/></p></body></html>", None))
        self.example_activity_label_2.setText(_translate("MainWindow", "example_activity", None))
        self.tabControl.setTabText(self.tabControl.indexOf(self.tab), _translate("MainWindow", "Schedule Viewer", None))
        self.label_6.setText(_translate("MainWindow", "Thing", None))
        self.label_7.setText(_translate("MainWindow", "Thing 2", None))
        self.label_8.setText(_translate("MainWindow", "Thing 3", None))
        self.label_9.setText(_translate("MainWindow", "Thing 4", None))
        self.label_10.setText(_translate("MainWindow", "Thing 5", None))
        self.schedule_viewer_label_2.setText(_translate("MainWindow", "Schedule Creator", None))
        self.example_zone_3.setToolTip(_translate("MainWindow", "some other zone", None))
        self.example_event_2.setToolTip(_translate("MainWindow", "some event", None))
        self.example_zone_4.setToolTip(_translate("MainWindow", "some zone", None))
        self.example_time_label_11.setText(_translate("MainWindow", "12:00 AM", None))
        self.example_time_label_12.setText(_translate("MainWindow", "12:15 AM", None))
        self.example_time_label_13.setText(_translate("MainWindow", "12:30 AM", None))
        self.example_time_label_14.setText(_translate("MainWindow", "12:45 AM", None))
        self.example_time_label_15.setText(_translate("MainWindow", "1:00 AM", None))
        self.example_time_label_16.setText(_translate("MainWindow", "1:15 AM", None))
        self.example_time_label_17.setText(_translate("MainWindow", "1:30 AM", None))
        self.example_time_label_18.setText(_translate("MainWindow", "1:45 AM", None))
        self.example_time_label_19.setText(_translate("MainWindow", "2:00 AM", None))
        self.example_time_label_20.setText(_translate("MainWindow", "2:15 AM", None))
        self.add_activity_button.setText(_translate("MainWindow", "Add Activity", None))
        self.example_activity_button_1.setToolTip(_translate("MainWindow", "some activity info", None))
        self.example_activity_button_1.setText(_translate("MainWindow", "example_activity", None))
        self.example_activity_button_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>LENGTH: 15 </p><p>START TIME: 10:22 </p><p>END TIME: 10:37</p></body></html>", None))
        self.example_activity_button_2.setText(_translate("MainWindow", "example_activity", None))
        self.tabControl.setTabText(self.tabControl.indexOf(self.tab_2), _translate("MainWindow", "Scheduler Creator", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Console", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Errors", None))
        self.help_button.setText(_translate("MainWindow", "Help", None))

